baseurl = "https://www.bioitee.com/"
RelativeURLs=true
CanonifyURLs=true
languageCode = "zh-cn"				# html的lang属性值
DefaultContentLanguage = "zh-cn"		# 默认内容语言用于选择i18n语言模板
title = "Bio IT 爱好者"
theme = "ICS-Hugo-Theme"
#googleAnalytics = "UA-112592341-1"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
hasCJKLanguage = true				# .WordCount works correctly for chinese
enableEmoji = true
footnotereturnlinkcontents = "↩"
MetaDataFormat = "yaml" 			# format of a new post
enableGitInfo = false
publishDir = "public"


[[menu.main]]
    name = "首页"
    url = "/"
    weight = 1

[[menu.main]]
    name = "关于"
    url = "/about/"
    weight = 2

[params]
    siteurl          = "https://www.bioitee.com/"
    description      = "Welcome to the site of BioITee."
    disqusURL        = ""
    customJS         = []
    githubContentURL = ""
    highlightjsTheme = "https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@11.3.1/build/styles/github.min.css"
    dateFormat       = "2019-01-01"	
    loadTypekit      = false
    recentPosts      = false			#首页最近更新文章

[params.footer]
    copyright = "<br/><br/>&copy; Powered by [ICS-Hugo-Theme](https://github.com/shenweiyan/ICS-Hugo-Theme) and [Hugo](https://gohugo.io) | [Bio IT 爱好者](https://www.bioitee.com/) 2018 - {year} | [粤ICP备16023717号](http://beian.miit.gov.cn/)<br/>"
    moreinfo = "<br/><br/>[![yuque](https://img.shields.io/badge/BioIT-语雀知识库-blueviolet)](https://www.yuque.com/bioitee) [![wechat](https://img.shields.io/badge/BioITee-微信公众号-important)](https://apps-db.oss-cn-shenzhen.aliyuncs.com/bioitee/bioitee.png) [![GitHub](https://img.shields.io/badge/GitHub-BioITee-blue)](https://github.com/bioitee) [![bioitee](https://img.shields.io/badge/官网主页-BioIT爱好者-green)](https://www.bioitee.com/)"

[params.author]
    en = "BioITee"
    cn = "BioITee"

[params.logo.en]
    img = ""
    url = "/"
    alt = "Steven Shum"
    tag = ""

[params.lang.edit]
    cn = "编辑"
[params.lang.license]
    cn = "版权"
[params.lang.subscribe]
    cn = "订阅"

#disqusShortname = ""			# 关闭 disqus 评论
[params.utteranc]
    enable    = true
    repo      = "bioitee/Community"	# utteranc 的评论默认存储在 github，这里填写你的 github repo，格式为 owner/repo
    issueTerm = "title"			# 表示你选择以那种方式让github issue的评论和你的文章关联可以选择默认的 pathname。
    theme     = "github-light"		# 样式主题


[taxonomies]
    tag      = "tags"
    series   = "series"
    category = "categories"

[markup.goldmark.renderer]
    unsafe   = true
